spring:
  data:
    redis:
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:3000ms}
      password: ${REDIS_PASSWORD:}

      master:
        host: ${REDIS_MASTER_HOST:localhost}
        port: ${REDIS_MASTER_PORT:6379}
        lettuce:
          pool:
            max-active: 10
            max-idle: 5
            min-idle: 2

      replica:
        host: ${REDIS_REPLICA_HOST:localhost}
        port: ${REDIS_REPLICA_PORT:6380}
        lettuce:
          pool:
            max-active: 20
            max-idle: 10
            min-idle: 5