decorator:
  datasource:
    p6spy:
      enable-logging: false
      multiline: false
      log-format: "%(sqlSingleLine)"

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    time-zone: Asia/Seoul
